---
# tasks file for minikube
- name: include assert.yml
  include_tasks: assert.yml

- name: install requirements
  package:
    name: "{{ minikube_requirements }}"
    state: present

- name: install minikube (apt)
  apt:
    deb: "{{ item }}"
    state: present
  when:
    - ansible_os_family == "Debian"
  loop: "{{ minikube_packages }}"

- name: install minikube (yum)
  yum:
    name: "{{ minikube_packages }}"
    state: present
    disable_gpg_check: yes
  when:
    - ansible_os_family == "RedHat"

- name: start minikube once
  command: "{{ minikube_command }}"
  args:
    creates: nothing
  when:
    - ansible_connection != "docker"
