---
- name: Converge
  hosts: all
  become: yes
  gather_facts: no

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.epel
    - role: robertdebock.python_pip
    - role: robertdebock.docker
    - role: robertdebock.kubectl
    - role: robertdebock.sysctl
      sysctl_items:
        name: net.bridge.bridge-nf-call-iptables
        value: 1
