---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint:
  name: yamllint
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  # - name: minikube-debian
  #   box: debian/stretch64
  - name: minikube-fedora
    box: fedora/30-cloud-base
    # cpus: 2
    provider_cpus: 2
provisioner:
  name: ansible
  playbooks:
    prepare: ../resources/prepare.yml
    converge: ../resources/playbook.yml
  lint:
    name: ansible-lint
    options:
      exclude:
        - meta/version.yml
        - meta/exception.yml
  inventory:
    host_vars:
      minikube-fedora:
        ansible_python_interpreter: /usr/bin/python3
scenario:
  name: vagrant
