---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint:
  name: yamllint
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: minikube-fedora
    box: fedora/30-cloud-base
    cpus: 2
    memory: 1024
provisioner:
  name: ansible
  playbooks:
    prepare: ../resources/prepare.yml
    converge: ../resources/playbook.yml
  inventory:
    host_vars:
      minikube-fedora:
        ansible_python_interpreter: /usr/bin/python3
scenario:
  name: vagrant
